$schema: https://json-schema.org/draft/2020-12/schema
description: A data entity used or generated during workflow execution
type: object
properties:
  '@id':
    type: string
    format: uri
    description: Unique identifier for the artifact
  '@type':
    const: Artifact
    description: Type of the entity (must be Artifact)
  describedByParameter:
    type: string
    format: uri
    description: Links to the parameter description (Input or Output) that this artifact corresponds to
  value:
    description: The actual value or reference to the artifact data
  wasOutputFrom:
    type: string
    format: uri
    description: The process run that generated this artifact
  checksum:
    type: object
    properties:
      algorithm:
        type: string
        enum: ["MD5", "SHA-1", "SHA-256", "SHA-512"]
      value:
        type: string
    description: Checksum information for data integrity
required:
  - '@id'
  - '@type'
